// Regenerates src/generated/<group>/<Name>.ts from artifacts/<group>/<Name>.json.
// ABIs are committed artifacts, never hand-edited; this script is the only writer of generated/.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, basename } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const artifacts = join(root, 'artifacts');
const generated = join(root, 'src', 'generated');

for (const group of readdirSync(artifacts)) {
  const outDir = join(generated, group);
  mkdirSync(outDir, { recursive: true });
  for (const file of readdirSync(join(artifacts, group))) {
    if (!file.endsWith('.json')) continue;
    const name = basename(file, '.json');
    const abi = JSON.parse(readFileSync(join(artifacts, group, file), 'utf8'));
    const body = `// Generated by scripts/gen-abis.mjs from artifacts/${group}/${file}. Do not edit.\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
    writeFileSync(join(outDir, `${name}.ts`), body);
    console.log(`wrote src/generated/${group}/${name}.ts`);
  }
}
