// Regenerates src/generated/<group>/<Name>.ts from artifacts/<group>/<Name>.json, refreshing the
// Spirith artifacts from contracts/out first. ABIs are committed artifacts, never hand-edited;
// this script is the only writer of artifacts/spirith and generated/.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const artifacts = join(root, 'artifacts');
const generated = join(root, 'src', 'generated');
const forgeOut = join(root, '..', '..', 'contracts', 'out');

const SPIRITH_CONTRACTS = ['SpirithVault', 'MockYieldAdapter'];
for (const name of SPIRITH_CONTRACTS) {
  const built = join(forgeOut, `${name}.sol`, `${name}.json`);
  if (!existsSync(built)) continue;
  const { abi } = JSON.parse(readFileSync(built, 'utf8'));
  mkdirSync(join(artifacts, 'spirith'), { recursive: true });
  writeFileSync(join(artifacts, 'spirith', `${name}.json`), JSON.stringify(abi));
  console.log(`refreshed artifacts/spirith/${name}.json from contracts/out`);
}

for (const group of readdirSync(artifacts)) {
  const outDir = join(generated, group);
  mkdirSync(outDir, { recursive: true });
  for (const file of readdirSync(join(artifacts, group))) {
    if (!file.endsWith('.json')) continue;
    const name = basename(file, '.json');
    const abi = JSON.parse(readFileSync(join(artifacts, group, file), 'utf8'));
    const body = `// Generated by scripts/gen-abis.mjs from artifacts/${group}/${file}. Do not edit.\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
    writeFileSync(join(outDir, `${name}.ts`), body);
    console.log(`wrote src/generated/${group}/${name}.ts`);
  }
}
