// Renders everything the subgraph takes from elsewhere so nothing here is hand-typed twice:
// ABIs from @spirith/core's committed artifacts, the vault address and start block from the
// deploy JSON, the ENS addresses and start blocks from core's ENS deployment JSON. Writes abis/, subgraph.yaml and
// src/config.ts, all git-ignored. `subgraph.template.yaml` is the source of the manifest.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const core = join(root, '..', 'core');

const ABIS = [
  ['ens', 'ETHRegistrar'],
  ['ens', 'ETHRegistry'],
  ['spirith', 'SpirithVault'],
];
mkdirSync(join(root, 'abis'), { recursive: true });
for (const [group, name] of ABIS) {
  const abi = readFileSync(join(core, 'artifacts', group, `${name}.json`), 'utf8');
  writeFileSync(join(root, 'abis', `${name}.json`), abi);
}

// One environment per build (SPIRITH_ENV, default hackathon): its ENSv2 set and creation blocks
// from core's deployments/ens/<env>.json, the vault from deployments/<env>.json.
const env = process.env.SPIRITH_ENV ?? 'hackathon';
const readJson = path => JSON.parse(readFileSync(path, 'utf8'));
const ens = readJson(join(core, 'deployments', 'ens', `${env}.json`));
const deployment = readJson(join(core, 'deployments', `${env}.json`));
if (deployment.chainId !== ens.chainId)
  throw new Error(`${env}: vault and ENS set are on different chains`);
const NETWORKS = { 11155111: 'sepolia', 1: 'mainnet' };
const network = NETWORKS[ens.chainId];
if (!network) throw new Error(`no Graph network name for chain id ${ens.chainId}`);

const values = {
  network,
  ethRegistrar: ens.ethRegistrar,
  ethRegistrarStartBlock: ens.startBlock.ethRegistrar,
  ethRegistry: ens.ethRegistry,
  ethRegistryStartBlock: ens.startBlock.ethRegistry,
  spirithVault: deployment.spirithVault,
  spirithVaultStartBlock: deployment.block,
};

const template = readFileSync(join(root, 'subgraph.template.yaml'), 'utf8');
const manifest = template.replace(/\{\{(\w+)\}\}/g, (_, key) => {
  if (!(key in values)) throw new Error(`no value for {{${key}}}`);
  return String(values[key]);
});
writeFileSync(join(root, 'subgraph.yaml'), manifest);

const config = `// Generated by scripts/prepare.mjs from @spirith/core. Do not edit.
import { Bytes } from '@graphprotocol/graph-ts';

export const SPIRITH_VAULT = Bytes.fromHexString('${values.spirithVault}');
/** The vault's referrer hash: its address left-padded to 32 bytes (spec §4.1 step 4). */
export const SPIRITH_REFERRER = Bytes.fromHexString(
  '0x000000000000000000000000${values.spirithVault.slice(2).toLowerCase()}',
);
`;
writeFileSync(join(root, 'src', 'config.ts'), config);
console.log(`subgraph: wrote abis/, subgraph.yaml, src/config.ts for the ${env} environment`);
