// Renders everything the subgraph takes from elsewhere so nothing here is hand-typed twice:
// ABIs from @spirith/core's committed artifacts, the vault address and start block from the
// deploy JSON, the ENS addresses from core's registry. Writes abis/, subgraph.yaml and
// src/config.ts, all git-ignored. `subgraph.template.yaml` is the source of the manifest.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const core = join(root, '..', 'core');

const ABIS = [
  ['ens', 'ETHRegistrar'],
  ['ens', 'ETHRegistry'],
  ['spirith', 'SpirithVault'],
];
mkdirSync(join(root, 'abis'), { recursive: true });
for (const [group, name] of ABIS) {
  const abi = readFileSync(join(core, 'artifacts', group, `${name}.json`), 'utf8');
  writeFileSync(join(root, 'abis', `${name}.json`), abi);
}

const deployment = JSON.parse(readFileSync(join(core, 'deployments', 'sepolia.json'), 'utf8'));
// Mirrors packages/core/src/ens/addresses.ts (the TS module cannot be imported before a build).
const addresses = readFileSync(join(core, 'src', 'ens', 'addresses.ts'), 'utf8');
const ensAddress = key => {
  const m = addresses.match(new RegExp(`${key}: '(0x[0-9a-fA-F]{40})'`));
  if (!m) throw new Error(`address ${key} not found in core/src/ens/addresses.ts`);
  return m[1];
};

// Contract creation blocks on Sepolia, from Etherscan (2026-09-08); the registry precedes the
// registrar by 17 blocks and both precede the first registration.
const values = {
  ethRegistrar: ensAddress('ethRegistrar'),
  ethRegistrarStartBlock: 11383914,
  ethRegistry: ensAddress('ethRegistry'),
  ethRegistryStartBlock: 11383897,
  spirithVault: deployment.spirithVault,
  spirithVaultStartBlock: deployment.block,
};

const template = readFileSync(join(root, 'subgraph.template.yaml'), 'utf8');
const manifest = template.replace(/\{\{(\w+)\}\}/g, (_, key) => {
  if (!(key in values)) throw new Error(`no value for {{${key}}}`);
  return String(values[key]);
});
writeFileSync(join(root, 'subgraph.yaml'), manifest);

const config = `// Generated by scripts/prepare.mjs from @spirith/core. Do not edit.
import { Bytes } from '@graphprotocol/graph-ts';

export const SPIRITH_VAULT = Bytes.fromHexString('${values.spirithVault}');
/** The vault's referrer hash: its address left-padded to 32 bytes (spec §4.1 step 4). */
export const SPIRITH_REFERRER = Bytes.fromHexString(
  '0x000000000000000000000000${values.spirithVault.slice(2).toLowerCase()}',
);
`;
writeFileSync(join(root, 'src', 'config.ts'), config);
console.log('subgraph: wrote abis/, subgraph.yaml, src/config.ts');
